[package]
name = "diamond-tools-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ethabi = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
ethers-contract = { version = "2.0.8" }
thiserror = { workspace = true }

[dev-dependencies]
once_cell = "1.8.0"
