[package]
name = "diamond-tools-core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.43"
ethabi = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
once_cell = "1.8.0"
